name: EAS Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - preview
        - development

jobs:
  build:
    name: Build and submit app
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            eas build --platform all --profile ${{ github.event.inputs.profile }} --non-interactive
          else
            eas build --platform all --profile production --non-interactive
          fi

      - name: Submit to stores (only for production builds)
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.profile == 'production')
        run: eas submit --platform all --non-interactive
