name: EAS Update (OTA)
on:
  push:
    branches: [develop, preview]
  pull_request:
    branches: [main]

jobs:
  update:
    name: Publish OTA Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish OTA Update
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            eas update --branch development --message "Update from develop branch"
          elif [ "${{ github.ref }}" = "refs/heads/preview" ]; then
            eas update --branch preview --message "Update from preview branch"
          else
            eas update --branch preview --message "Update from PR #${{ github.event.number }}"
          fi
